# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaming_host?useSSL=false
    username: root
    password: coderslab
    driver-class-name: com.mysql.jdbc.Driver

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      port: 8080
  # ===============================
  # = Thymeleaf configurations
  # ===============================
  thymeleaf:
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    locale: pl_PL
    locale-resolver: fixed

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
